/**
 * Tenant domain provisioning — direct nginx + Let's Encrypt approach.
 *
 * Why not Plesk REST API anymore: the standard Plesk path (POST /api/v2/domains)
 * counts each tenant against the Plesk subscription's lim_dom quota. With
 * Web Admin Edition that's 10 domains total — not viable for a multi-tenant
 * platform. Domain aliases were attempted as a workaround but Plesk doesn't
 * regenerate the parent's nginx server_name when the alias is added.
 *
 * Replacement: skip Plesk's domain-management layer entirely.
 *
 *   1. Issue a Let's Encrypt cert via Plesk's bundled LE CLI, using the
 *      webroot at /var/www/vhosts/default/htdocs. Doesn't count against
 *      the domain quota.
 *
 *   2. Write a per-tenant nginx config to
 *      /etc/nginx/conf.d/legalos-tenants/<host>.conf with two server blocks:
 *        - :80  → ACME challenge + 301 to HTTPS
 *        - :443 → SSL + reverse-proxy to the Next.js app
 *
 *   3. systemctl reload nginx — picks up the new config without dropping
 *      existing connections.
 *
 * The Next.js app (running locally on :3000) sees Host: <tenant> and
 * resolves it via resolveSiteByHost() to the correct Site row.
 */
import { promises as fs } from 'fs'
import { spawn } from 'child_process'
import path from 'path'

export type ProvisionStep = { step: string; ok: boolean; detail?: string }
export type ProvisionResult = {
  ok: boolean
  /** Kept named `plesk_domain_id` for DB schema back-compat. Now holds the host. */
  plesk_domain_id: string | null
  steps: ProvisionStep[]
  error?: string
}

const TENANT_NGINX_DIR = '/etc/nginx/conf.d/legalos-tenants'
const LE_CERT_DIR = '/opt/psa/var/modules/letsencrypt/etc/live'
const ACME_WEBROOT = '/var/www/vhosts/default/htdocs'

const proxyTarget = (): string => process.env.PLESK_PROXY_TARGET ?? 'http://127.0.0.1:3000'
const ownerEmail = (): string => process.env.PLESK_OWNER_EMAIL ?? 'team@legenex.com'
const ipAddress = (): string | null => process.env.PLESK_IP_ADDRESS || null

type ShellResult = { code: number; stdout: string; stderr: string }
const shell = (cmd: string, args: string[], opts: { timeoutMs?: number } = {}): Promise<ShellResult> =>
  new Promise((resolve) => {
    const timeoutMs = opts.timeoutMs ?? 120_000
    const child = spawn(cmd, args, { stdio: ['ignore', 'pipe', 'pipe'] })
    let stdout = ''
    let stderr = ''
    child.stdout.on('data', (d: Buffer) => { stdout += d.toString() })
    child.stderr.on('data', (d: Buffer) => { stderr += d.toString() })
    const timer = setTimeout(() => child.kill('SIGKILL'), timeoutMs)
    child.on('close', (code) => {
      clearTimeout(timer)
      resolve({ code: code ?? -1, stdout, stderr })
    })
    child.on('error', (err) => {
      clearTimeout(timer)
      resolve({ code: -1, stdout, stderr: stderr || err.message })
    })
  })

const isSafeHost = (host: string): boolean =>
  /^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?)+$/i.test(host)

const tenantConfigPath = (host: string): string => path.join(TENANT_NGINX_DIR, `${host}.conf`)

const renderTenantNginxConfig = (host: string): string => {
  const ip = ipAddress()
  const listen80 = ip ? `${ip}:80` : '80'
  const listen443 = ip ? `${ip}:443` : '443'
  const target = proxyTarget()
  return `# LegalOS tenant: ${host}
# Generated by src/lib/plesk/provision-domain.ts at ${new Date().toISOString()}

server {
    listen ${listen80};
    server_name ${host} www.${host};

    location ^~ /.well-known/acme-challenge/ {
        root ${ACME_WEBROOT};
        default_type text/plain;
        allow all;
    }

    location / { return 301 https://$host$request_uri; }
}

server {
    listen ${listen443} ssl;
    http2 on;
    server_name ${host} www.${host};

    ssl_certificate     ${LE_CERT_DIR}/${host}/fullchain.pem;
    ssl_certificate_key ${LE_CERT_DIR}/${host}/privkey.pem;

    client_max_body_size 50m;

    location ^~ /.well-known/acme-challenge/ {
        root ${ACME_WEBROOT};
        default_type text/plain;
        allow all;
    }

    location / {
        proxy_pass ${target};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 60s;
        proxy_send_timeout 60s;
    }
}
`
}

const issueLetsEncryptCert = async (host: string): Promise<{ ok: boolean; detail: string }> => {
  const args = [
    'bin', 'extension', '--exec', 'letsencrypt', 'cli.php',
    '-d', host,
    '-m', ownerEmail(),
    '-w', ACME_WEBROOT,
  ]
  const result = await shell('plesk', args, { timeoutMs: 180_000 })
  if (result.code !== 0) {
    const tail = (result.stderr || result.stdout || 'LE CLI failed').trim().split('\n').slice(-5).join(' | ')
    return { ok: false, detail: tail }
  }
  try {
    await fs.access(`${LE_CERT_DIR}/${host}/fullchain.pem`)
    await fs.access(`${LE_CERT_DIR}/${host}/privkey.pem`)
  } catch {
    return { ok: false, detail: 'LE reported success but cert files missing on disk' }
  }
  return { ok: true, detail: `cert at ${LE_CERT_DIR}/${host}/fullchain.pem` }
}

const writeAndReloadNginx = async (host: string): Promise<{ ok: boolean; detail: string }> => {
  const filePath = tenantConfigPath(host)
  await fs.mkdir(TENANT_NGINX_DIR, { recursive: true })
  await fs.writeFile(filePath, renderTenantNginxConfig(host), { mode: 0o644 })
  const test = await shell('nginx', ['-t'])
  if (test.code !== 0) {
    await fs.unlink(filePath).catch(() => undefined)
    const tail = (test.stderr || test.stdout).trim().split('\n').slice(-3).join(' | ')
    return { ok: false, detail: `nginx -t failed: ${tail}` }
  }
  const reload = await shell('systemctl', ['reload', 'nginx'])
  if (reload.code !== 0) {
    return { ok: false, detail: `nginx reload failed: ${(reload.stderr || reload.stdout).trim()}` }
  }
  return { ok: true, detail: filePath }
}

export const provisionDomainInPlesk = async (args: { host: string }): Promise<ProvisionResult> => {
  const steps: ProvisionStep[] = []
  const host = args.host.trim().toLowerCase()

  if (!isSafeHost(host)) {
    return {
      ok: false,
      plesk_domain_id: null,
      steps: [{ step: 'guard', ok: false, detail: `unsafe hostname: ${host}` }],
      error: `unsafe hostname: ${host}`,
    }
  }

  const cert = await issueLetsEncryptCert(host)
  steps.push({ step: 'letsencrypt', ok: cert.ok, detail: cert.detail })
  if (!cert.ok) return { ok: false, plesk_domain_id: null, steps, error: `LE cert: ${cert.detail}` }

  const nginx = await writeAndReloadNginx(host)
  steps.push({ step: 'nginx', ok: nginx.ok, detail: nginx.detail })
  if (!nginx.ok) return { ok: false, plesk_domain_id: host, steps, error: nginx.detail }

  return { ok: true, plesk_domain_id: host, steps }
}

export const unprovisionDomainInPlesk = async (args: { pleskDomainId: string }): Promise<{ ok: boolean; error?: string }> => {
  const host = args.pleskDomainId.trim().toLowerCase()
  if (!isSafeHost(host)) return { ok: false, error: `unsafe hostname: ${host}` }

  const cfgPath = tenantConfigPath(host)
  try {
    await fs.unlink(cfgPath)
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== 'ENOENT') {
      return { ok: false, error: `failed to remove nginx config: ${(err as Error).message}` }
    }
  }

  await shell('plesk', [
    'bin', 'extension', '--exec', 'letsencrypt', 'cli.php',
    '-d', host,
    '--revoke',
  ], { timeoutMs: 60_000 }).catch(() => undefined)

  const reload = await shell('systemctl', ['reload', 'nginx'])
  if (reload.code !== 0) {
    return { ok: false, error: `nginx reload failed: ${reload.stderr || reload.stdout}` }
  }

  return { ok: true }
}

/**
 * Provisioning no longer requires PLESK_API_URL / PLESK_API_KEY. The LE CLI
 * runs as the local root systemd service and nginx config is direct filesystem
 * access. Only PLESK_PROXY_TARGET and (optionally) PLESK_IP_ADDRESS are read.
 */
export const pleskIsConfigured = (): boolean => {
  if ((process.env.LEGALOS_DISABLE_PROVISIONING ?? 'false').toLowerCase() === 'true') return false
  return true
}
